language: node_js

node_js:
  - node # Current stable

install:
  - npm install nightwatch

before_script:
  - node --version
  - npm --version

script: 'true'

jobs:
  include:
    - stage: "Nightwatch UI Testing"
    - name: "QA2"
      script:  nightwatch --env qa2_chrome --env-var "process.env.BROWSERSTACK_USER=$BROWSERSTACK_USER" --env-var "process.env.BROWSERSTACK_KEY=$BROWSERSTACK_KEY" --env-var "process.env.DSA_USERNAME_TANDEM=$DSA_USERNAME_TANDEM" --env-var "process.env.DSA_PASSWORD_TANDEM=$DSA_PASSWORD_TANDEM" --env-var "process.env.OTP_SECRET=$OTP_SECRET" --env-var "process.env.GMAIL_USERNAME=$GMAIL_USERNAME" --env-var "process.env.GMAIL_PASSWORD=$GMAIL_PASSWORD"
    - name: "QA1"
      script:  nightwatch --env qa1_chrome --env-var "process.env.BROWSERSTACK_USER=$BROWSERSTACK_USER" --env-var "process.env.BROWSERSTACK_KEY=$BROWSERSTACK_KEY" --env-var "process.env.DSA_USERNAME_TANDEM=$DSA_USERNAME_TANDEM" --env-var "process.env.DSA_PASSWORD_TANDEM=$DSA_PASSWORD_TANDEM" --env-var "process.env.OTP_SECRET=$OTP_SECRET" --env-var "process.env.GMAIL_USERNAME=$GMAIL_USERNAME" --env-var "process.env.GMAIL_PASSWORD=$GMAIL_PASSWORD"
    - name: "PRD"
      script:  nightwatch --env prd_chrome --env-var "process.env.BROWSERSTACK_USER=$BROWSERSTACK_USER" --env-var "process.env.BROWSERSTACK_KEY=$BROWSERSTACK_KEY" --env-var "process.env.DSA_USERNAME_TANDEM=$DSA_USERNAME_TANDEM" --env-var "process.env.DSA_PASSWORD_TANDEM=$DSA_PASSWORD_TANDEM" --env-var "process.env.OTP_SECRET=$OTP_SECRET" --env-var "process.env.GMAIL_USERNAME=$GMAIL_USERNAME" --env-var "process.env.GMAIL_PASSWORD=$GMAIL_PASSWORD"