version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  run_ui_tests:
    working_directory: ~/tidepool-org/webuitests
    macos:
      xcode: '10.1.0'
    steps:
      - checkout
      - node/install
      - run: node --version
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm test

workflows:
  test_my_app:
    jobs:
      - run_ui_tests
