version: 2.1
orbs:
  node: circleci/node@4.2.0
parameters:
  testEnvironment:
      type: string
      default: "testParallel"

jobs:
  test:
    working_directory: ~/tidepool-org/webuitests
    macos:
      xcode: '13.0.0'
    resource_class: large
    steps:
      - checkout
      - node/install
      - run: node --version
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
         name: Run Parallel Tests on Chosen Environments
         command: npm run << pipeline.parameters.testEnvironment >>
      - run:
          name: Consolidate Test Report
          command: npm run merge-reports
      - store_artifacts:
          path: ./vrt/diff
      - store_artifacts:
          path: ./vrt/latest
      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          path: tests_output/testresults.xml
      - when:
          condition:
            and:
              - equal: ["testqa2All", << pipeline.parameters.testEnvironment >> ]
          steps:
          - run:
              name: Get API token
              command: |
                echo export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$CLIENT_ID\",\"client_secret\": \"$CLIENT_SECRET\" }" https://xray.cloud.xpand-it.com/api/v1/authenticate| tr -d '"') >> $BASH_ENV
                source $BASH_ENV
          - run: 
              name: Send Results to JIRA
              command: 'curl -H "Content-Type: text/xml" -H "Authorization: Bearer $token" --data @target/tests_output/testresults.xml  "https://xray.cloud.xpand-it.com/api/v1/import/execution/junit?projectKey=WEB&testPlanKey=WEB-1746"'

workflows:
  commit-workflow:
    jobs:
      - test
  scheduled-workflow:
    triggers:
      - schedule:
          filters:
            branches:
              only:
                - main
          cron: "0 8 * * *"
    jobs:
      - test
