version: 2.1
orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.4.8
  slack: circleci/slack@4.1
parameters:
  testEnvironment:
      type: string
      default: "testParallel"
  testExecKey:
      type: string
      default: "none"
jobs:
  test:
    working_directory: ~/tidepool-org/webuitests
    docker: 
      - image: cimg/node:lts-browsers
    environment:
      TEST_EXECUTION_KEY: << pipeline.parameters.testExecKey >>
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install
      - run: node --version
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
         name: Run Parallel Tests on Chosen Environments
         command: npm run << pipeline.parameters.testEnvironment >>
      - run:
          name: Consolidate Test Report
          command: npm run merge-reports
          when: always
      - store_artifacts:
          path: tests_output/nightwatch-html-report
      - store_artifacts:
          path: vrt/latest
      - store_artifacts:
          path: vrt/diff
      - store_artifacts:
          path: vrt/baseline/ui
      - store_test_results:
          path: tests_output/testresults.xml
      - slack/notify:
          event: fail
          branch_pattern: main
          mentions: '<@SH7G29GKD>'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " The Tidepool Web UI tests have *failed*. :sad_tapani: \n\n QA will confirm resolution details in thread"
                  }
                }
              ]
            }
      - slack/notify:
          event: pass
          branch_pattern: main
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                      "text": " The Tidepool Web UI tests have passed. :catjam:  \n\n"
                  }
                }
              ]
            }
      - unless:
          condition:
            and:
              - equal: ["testParallel", << pipeline.parameters.testEnvironment >> ]
          steps:
          - run:
              name: Gather Test Evidence
              command: node utilities/browserstackEvidenceDownload.js
              when: always
          - run:
              name: Get API token
              command: |
                echo export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$CLIENT_ID\",\"client_secret\": \"$CLIENT_SECRET\" }" https://xray.cloud.getxray.app/api/v1/authenticate| tr -d '"') >> $BASH_ENV
                source $BASH_ENV
              when: always
          - run: 
              name: Send Results to XRAY
              command: 'curl -H "Content-Type: text/xml" -H "Authorization: Bearer $token" --data @tests_output/testresults.xml  "https://xray.cloud.getxray.app/api/v1/import/execution/junit?testExecKey=<< pipeline.parameters.testExecKey >>"'
              when: always
          - run:
              name: Add Test Evidence to JIRA
              command: node utilities/sendTestEvidenceToJira.js
              when: always
workflows:
  commit-workflow:
    jobs:
      - test
  scheduled-workflow:
    triggers:
      - schedule:
          filters:
            branches:
              only:
                - main
          cron: "0 8 * * *"
    jobs:
      - test
