version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  test:
    working_directory: ~/tidepool-org/webuitests
    macos:
      xcode: '13.0.0'
    resource_class: large
    steps:
      - checkout
      - node/install
      - run: node --version
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
         name: Run Parallel Tests on All Environments
         command: npm run testParallel
      # - run:
      #     name: Run qa1 Tests
      #     command: npm run testqa1Seq
      # - run:
      #     name: Run qa2 Tests
      #     command: npm run testqa2Seq
      # - run:
      #     name: Run prd Tests
      #     command: npm run testprdSeq
      # - run:
      #     name: Run int Tests
      #     command: npm run testintSeq

workflows:
  commit-workflow:
    jobs:
      - test
  scheduled-workflow:
    triggers:
      - schedule:
          filters:
            branches:
              only:
                - main
          cron: "0 8 * * *"
    jobs:
      - test
